### ISSUE TITLE
 Request req_7qTbBITXPt3pCH: This API call cannot be made with a publishable API key

### ISSUE THREAD

**Issue by thisismsreddy** [iktw/django-rest-framework-stripe#3]
stripe.error.AuthenticationError: Request req_7qTbBITXPt3pCH: This API call cannot be made with a publishable API key. Please use a secret API key. You can find a list of your API keys at https://dashboard.stripe.com/account/apikeys.

I did give the Keys right but still i got this error

**Comment by ezequieloliveiralima** [comment]
Are you using sk_test_ ? When you are declaring:
require('stripe')('sk_test_')

**Comment by thisismsreddy** [comment]
I will look into that thanks
